server:
  port: 8000

eureka:
  instance:
    client:
      register-with-eureka: false
      fetch-registry: false
      sevice-url:
        defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      routes:
        - id: catalog-service
          uri: lb://CATALOG-SERVICE
          predicates:
            - Path=/catalog-service/**

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/**

        - id: second-service
          uri: http://localhost:8082/
          predicates:
            - Path=/second-service/**
